### PR TITLE
add multiplex if example notebook

### PR DESCRIPTION
**Pull request by ryanccarelli**
Add example demonstrating multiplex if pipeline on Nolan lab colorectal cancer TMA data

### CODE REVIEW

**Comment by jacobrosenthaldfci** [comment]
This is awesome! I think we just need to clean up a few small things and then it'll be ready! Here is what I'm thinking:

* Add a couple of sentences for intro, explaining what's going on etc. for a user who might have limited background knowledge
* Need to include a title in the notebook for the docs (# level)
* Add a few sentences to explain what each chunk is doing
* Suppress all the warnings/errors

**Comment by jacobrosenthaldfci** [comment]
Also let's merge to dev, not master

**Comment by ryanccarelli** [comment]
Thanks for your feedback, I made these improvements (and some others to clean up). Should be ready to go now

**Review by jacobrosenthaldfci — APPROVED** [review]
Awesome :) I think this will be really useful for people!!

**Pull request merged**
