### PR TITLE
remove calls to h5 resize by declaring full array on h5manager initialization

### PR DESCRIPTION
**Pull request by ryanccarelli**
This branch checks whether distributed performance is adversely impacted by dynamic resizing of h5.Datasets in h5manager.add_tile calls.

### CODE REVIEW

**Comment by dmbrundage** [comment]
I reran the slide in using a local dask client and received a MemoryError. Output below.
`---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<timed eval> in <module>

/opt/conda/lib/python3.9/site-packages/pathml/core/slide_data.py in run(self, pipeline, distributed, client, tile_size, tile_stride, level, tile_pad, overwrite_existing_tiles)
    310                 processed_tile_futures, with_results=True
    311             ):
--> 312                 self.tiles.add(tile)
    313 
    314         else:

/opt/conda/lib/python3.9/site-packages/pathml/core/tiles.py in add(self, tile)
     79                 f"can not add {type(tile)}, tile must be of type pathml.core.tiles.Tile"
     80             )
---> 81         self.h5manager.add_tile(tile)
     82         del tile
     83 

/opt/conda/lib/python3.9/site-packages/pathml/core/h5managers.py in add_tile(self, tile)
    152                 shape=arrayshape,
    153                 maxshape=maxshape,
--> 154                 data=np.zeros(arrayshape),
    155                 chunks=True,
    156                 compression="gzip",

MemoryError: Unable to allocate 42.7 GiB for an array with shape (32914, 58000, 3) and data type float64`

**Comment by jacobrosenthaldfci** [comment]
When initializing a h5py dataset, do we need to specify `data=np.zeros(arrayshape)` ?
Can we just use the shape parameter, plus `fillvalue=0` or something?
It looks like from the error message that the problem is in initializing the huge np zeros array. 
Another thing to try would be using int8 or float16 or something, instead of float64, as the datatype

**Comment by ryanccarelli** [comment]
Thanks for the suggestions, 
- I set fillvalue=0 and dtype=f16 in create_dataset().
- I added a test that adds the first tile from a large slide and checks memory usage.

**Comment by ryanccarelli** [comment]
Array initialization might not be the bottleneck. Possibly since h5py doesn't enable by default parallel writes the __setitem__ process is bottleneckings. 

There are potential fixes:
1. Install h5py with mpi https://stackoverflow.com/questions/58345261/configuring-h5py-with-mpio-using-anaconda-on-windows/59073514#59073514
2. Use parallel h5py
```python
from mpi4py import MPI
import h5py

rank = MPI.COMM_WORLD.rank  # The process ID (integer 0-3 for 4-process run)

f = h5py.File('parallel_test.hdf5', 'w', driver='mpio', comm=MPI.COMM_WORLD)

dset = f.create_dataset('test', (4,), dtype='i')
dset[rank] = rank

f.close()
```
https://docs.h5py.org/en/stable/mpi.html

**Comment by jacobrosenthaldfci** [comment]
Here is the benchmarking code from David:

````python
import cProfile
import pstats
import matplotlib.pyplot as plt
import numpy as np
 
from pathml.core import HESlide
 
%matplotlib inline
 
wsi = HESlide("../data/CMU-1.svs", name = "example")
 
from pathml.preprocessing import Pipeline, BoxBlur, TissueDetectionHE
 
pipeline = Pipeline([
    BoxBlur(kernel_size=15),
    TissueDetectionHE(mask_name = "tissue", min_region_size=500, 
                      threshold=30, outer_contours_only=True)
])
 
from dask.distributed import Client, LocalCluster
 
cluster = LocalCluster(n_workers=6)
client = Client(cluster)
 
print(client)
#run cProfile for parallel pipeline
cProfile.run(‘wsi.run(pipeline, distributed=True, client=client’)
 
#save results into profile results file with pstats and remove extraneous path from module names, sort by#name
p = pstats.Stats(‘profile_stats’)
p.strip_dirs().sort_stats(-1).print_stats()
 
# sort profile by cumulative time in a function and print 10 most significant lines
p.sort_stats(SortKey.cumulative.print_stats(10)
````

And here are the results of the benchmarking of the current implementation:

````
Thu Sep 30 21:04:14 2021    profile_stats
 
         1620909 function calls (1619167 primitive calls) in 463.498 seconds
 
   Ordered by: cumulative time
   List reduced from 461 to 10 due to restriction <10>
 
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  463.499  463.499 {built-in method builtins.exec}
        1    0.001    0.001  463.499  463.499 <string>:1(<module>)
        1    0.057    0.057  463.492  463.492 slide_data.py:244(run)
      150    0.002    0.000  402.103    2.681 tiles.py:70(add)
      150    2.021    0.013  402.101    2.681 h5managers.py:88(add_tile)
      300  363.382    1.211  363.424    1.211 dataset.py:790(__setitem__)
      151    0.002    0.000   47.080    0.312 slide_data.py:365(generate_tiles)
      151    0.004    0.000   47.055    0.312 slide_backends.py:137(generate_tiles)
      150    0.013    0.000   47.049    0.314 slide_backends.py:70(extract_region)
      150    0.000    0.000   42.416    0.283 __init__.py:218(read_region)
````

The goal of this PR should be to reduce the amount of time being spent on the `__setitem__` bottleneck

**Comment by dmbrundage** [comment]
I tried implementing the MPI solution but that appears to come with its own issues. We would essentially be working with MPI instead of dask-distributed, though dask has an MPI framework. Also, h5py cannot use filters in parallel with MP (shuffle, compression, etc..)

**Comment by jacobrosenthaldfci** [comment]
Thanks for looking into it! Agree that MPI might not be the best solution – especially because it could make environment setup even more complicated since h5py would need to be built with mpi support (which the version on pip doesn’t have I think)
 
Here are some other things that come to mind for looking into boosting performance:
 
1. Rewrite h5manager to minimize interactions with the h5 file as much as possible. For example, [here](https://github.com/Dana-Farber-AIOS/pathml/blob/master/pathml/core/h5managers.py#L126-L144) we could cache the shape as a class attribute instead of calling `self.h5["array"].shape` multiple times. From [this comment](https://github.com/h5py/h5py/issues/994#issuecomment-364767614) it seems like every time you call  `h5["array"]` or similar, it adds overhead by initializing a new python object and backing c objects. So we could possibly see big impact by reducing these.
2. Make sure that we are fully leveraging chunking. Right now we initialize the array with `chunks=True` which means that h5py tries to infer the chunk size. Maybe it would help to specify chunk size explicitly? (i.e. chunks = tile size). More info [here](https://support.hdfgroup.org/HDF5/doc/Advanced/Chunking/) and [here](https://docs.h5py.org/en/stable/high/dataset.html#chunked-storage)
    - Chunk size is recommended to be between 10KB and 1MB ([source](https://docs.h5py.org/en/stable/high/dataset.html#chunked-storage)) so maybe we are actually using tiles that are too big? e.g. the default tile size of 3000px is way bigger than 1MB.
3. Make sure we aren't using any fancy indexing, which seems to be slow for h5 in some cases (see [here](https://gist.github.com/rossant/7b4704e8caeb8f173084))

**Comment by ryanccarelli** [comment]
This work has moved to #231.

**Pull request closed without merging**
